'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DetallePedido
    Public Property DetallePedidoId As Integer
    Public Property IdProducto As Integer
    Public Property IdPedido As Integer
    Public Property Cantidad As Integer
    Public Property FechaAdiciDetaPedido As Date
    Public Property FechaModifiDetaPedido As Nullable(Of Date)

    Public Overridable Property Pedido As Pedido
    Public Overridable Property Producto As Producto

End Class
