'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Producto
    Public Property ProductoID As Integer
    Public Property Nombre As String
    Public Property Descripcion As String
    Public Property Stock As Integer
    Public Property Valor As Integer
    Public Property Departamento As Integer
    Public Property Activo As Boolean

    Public Overridable Property DetallePedido As ICollection(Of DetallePedido) = New HashSet(Of DetallePedido)

End Class
